import type { BoothLayout, BoothSettings, CropState } from '../types';

export interface Slot { x:number; y:number; w:number; h:number }
export function getSlots(layout:BoothLayout, gap:number):Slot[] {
  const pad=Math.max(28,gap*3.2);
  if(layout.id.startsWith('paired-')){const rows=Math.ceil(layout.poses/2),top=120,footer=130,w=(layout.width-pad*2-gap)/2,h=(layout.height-top-footer-pad-gap*(rows-1))/rows;return Array.from({length:layout.poses},(_,i)=>({x:pad+(i%2)*(w+gap),y:top+Math.floor(i/2)*(h+gap),w,h}));}
  if(layout.id==='strip-3'){const usable=layout.height-310-pad*2;return Array.from({length:3},(_,i)=>({x:pad,y:pad+82+i*(usable/3),w:layout.width-pad*2,h:usable/3-gap}));}
  if(layout.id==='strip-4'){const usable=layout.height-260-pad*2;return Array.from({length:4},(_,i)=>({x:pad,y:pad+48+i*(usable/4),w:layout.width-pad*2,h:usable/4-gap}));}
  if(layout.id==='strip-2'){const usable=layout.height-370-pad*2;return Array.from({length:2},(_,i)=>({x:pad,y:pad+110+i*(usable/2),w:layout.width-pad*2,h:usable/2-gap}));}
  if(layout.id==='grid-4'){const top=145,footer=175,w=(layout.width-pad*2-gap)/2,h=(layout.height-top-footer-pad-gap)/2;return Array.from({length:4},(_,i)=>({x:pad+(i%2)*(w+gap),y:top+Math.floor(i/2)*(h+gap),w,h}));}
  if(layout.id==='grid-6'){const top=135,footer=145,w=(layout.width-pad*2-gap*2)/3,h=(layout.height-top-footer-pad-gap)/2;return Array.from({length:6},(_,i)=>({x:pad+(i%3)*(w+gap),y:top+Math.floor(i/3)*(h+gap),w,h}));}
  if(layout.id==='album-square'){const size=Math.min(layout.width-210,layout.height-410);return [{x:(layout.width-size)/2,y:185,w:size,h:size}]}
  return [{x:58,y:170,w:layout.width-116,h:layout.height-390}];
}

const load=(src:string)=>new Promise<HTMLImageElement>((ok,no)=>{const image=new Image();image.onload=()=>ok(image);image.onerror=no;image.src=src});
const effectFilter=(effect:BoothSettings['frameEffect'])=>effect==='vivid'?'saturate(1.5) contrast(1.15)':effect==='mono'?'grayscale(1) contrast(1.25)':effect==='vintage'?'sepia(.55) contrast(.92) saturate(.85)':effect==='midnight'?'brightness(.58) contrast(1.35) saturate(.75)':effect==='soft'?'brightness(1.12) saturate(.75) contrast(.88)':'none';
const MATERIAL_IMAGES:Partial<Record<NonNullable<BoothSettings['frameStyle']>,string>>={'aurora-blue':'/frame-materials/aurora-blue.jpg','molten-red':'/frame-materials/molten-red.jpg','golden-brush':'/frame-materials/golden-brush.jpg','espresso-silk':'/frame-materials/espresso-silk.jpg','forest-light':'/frame-materials/forest-light.jpg','violet-satin':'/frame-materials/violet-satin.jpg','silver-flow':'/frame-materials/silver-flow.jpg','ember-chrome':'/frame-materials/ember-chrome.jpg','dream-flora':'/frame-materials/dream-flora.jpg','cosmic-violet':'/frame-materials/cosmic-violet.jpg','ethereal-aura':'/frame-materials/ethereal-aura.jpg','arctic-monkeys':'/frame-materials/albums/arctic-monkeys.jpg','1989':'/frame-materials/albums/1989.jpg','portrait-noir':'/frame-materials/albums/portrait-noir.jpg','ocean-blue':'/frame-materials/albums/ocean-blue.jpg','fearless-tv':'/frame-materials/albums/fearless-tv.jpg','blonde':'/frame-materials/albums/blonde.jpg','silk-sonic':'/frame-materials/albums/silk-sonic.jpg','after-hours':'/frame-materials/albums/after-hours.jpg','1975-self-titled':'/frame-materials/albums/1975-self-titled.jpg','reputation':'/frame-materials/albums/reputation.jpg','the-1975':'/frame-materials/albums/the-1975.jpg','folklore':'/frame-materials/albums/folklore.jpg'};
async function frameFill(x:CanvasRenderingContext2D,w:number,h:number,settings:BoothSettings){x.fillStyle=settings.frame;x.fillRect(0,0,w,h);const source=settings.frameStyle?MATERIAL_IMAGES[settings.frameStyle]:undefined;if(source){const image=await load(source);const scale=Math.max(w/image.width,h/image.height),dw=image.width*scale,dh=image.height*scale;x.save();x.filter=effectFilter(settings.frameEffect);x.drawImage(image,(w-dw)/2,(h-dh)/2,dw,dh);x.restore();x.save();x.globalCompositeOperation='color';x.globalAlpha=.66;x.fillStyle=settings.frame;x.fillRect(0,0,w,h);x.restore();return}if(settings.frameStyle==='solid')return;const tile=document.createElement('canvas');tile.width=80;tile.height=80;const t=tile.getContext('2d')!;t.fillStyle=settings.frame;t.fillRect(0,0,80,80);const dark='#352a2e',light='#fff8fa';
 if(['blush-grid','checker'].includes(settings.frameStyle||'solid')){t.fillStyle=light;t.fillRect(0,0,40,40);t.fillRect(40,40,40,40);if(settings.frameStyle==='checker'){t.fillStyle=dark;t.fillRect(40,0,40,40);t.fillRect(0,40,40,40)}}
 if(settings.frameStyle==='gingham'){t.globalAlpha=.45;t.fillStyle='#fff';t.fillRect(0,0,80,22);t.fillRect(0,44,80,22);t.fillRect(0,0,22,80);t.fillRect(44,0,22,80)}
 if(settings.frameStyle==='disco'){t.fillStyle='#171719';t.fillRect(0,0,80,80);for(let y=7;y<80;y+=14)for(let z=7;z<80;z+=14){t.fillStyle=(y+z)%28?'#aaa':'#fff';t.beginPath();t.arc(z,y,5,0,Math.PI*2);t.fill()}}
 if(settings.frameStyle==='cow'){t.fillStyle='#fff';t.fillRect(0,0,80,80);t.fillStyle='#171419';for(const [a,b,c,d] of [[15,15,16,11],[58,50,23,15],[12,72,20,13]] as number[][]){t.beginPath();t.ellipse(a,b,c,d,.4,0,Math.PI*2);t.fill()}}
 if(settings.frameStyle==='leopard'){t.fillStyle='#d2a870';t.fillRect(0,0,80,80);for(const [a,b] of [[18,18],[60,22],[35,60]] as number[][]){t.strokeStyle='#2b201b';t.lineWidth=7;t.beginPath();t.arc(a,b,10,0,Math.PI*1.6);t.stroke()}}
 if(settings.frameStyle==='waves'){t.strokeStyle='#65c2d0';t.lineWidth=7;for(let y=0;y<100;y+=20){t.beginPath();t.arc(0,y,22,0,Math.PI);t.arc(40,y,22,0,Math.PI);t.arc(80,y,22,0,Math.PI);t.stroke()}}
 if(settings.frameStyle==='denim'){t.fillStyle='#527fa0';t.fillRect(0,0,80,80);t.strokeStyle='#9ec0d5';t.lineWidth=3;for(let i=-80;i<160;i+=12){t.beginPath();t.moveTo(i,0);t.lineTo(i-80,80);t.stroke()}}
 if(settings.frameStyle==='floral'){t.fillStyle='#f5e6e9';t.fillRect(0,0,80,80);for(const [a,b] of [[18,18],[60,55]] as number[][]){t.fillStyle='#d66d8a';for(let q=0;q<6;q++){t.beginPath();t.arc(a+Math.cos(q)*9,b+Math.sin(q)*9,6,0,Math.PI*2);t.fill()}t.fillStyle='#f6dc7b';t.beginPath();t.arc(a,b,5,0,Math.PI*2);t.fill()}}
 if(settings.frameStyle==='night'){t.fillStyle='#242536';t.fillRect(0,0,80,80);t.fillStyle='#f7dd82';for(const [a,b] of [[12,16],[45,8],[68,38],[25,61],[57,70]] as number[][]){t.beginPath();t.arc(a,b,3,0,Math.PI*2);t.fill()}}
 if(settings.frameStyle==='sparkle'){const g=t.createLinearGradient(0,0,80,80);g.addColorStop(0,'#bba8aa');g.addColorStop(.35,'#fff');g.addColorStop(.65,'#d7c6c0');g.addColorStop(1,'#8d8187');t.fillStyle=g;t.fillRect(0,0,80,80)}
 const pattern=x.createPattern(tile,'repeat');if(pattern){x.save();x.filter=effectFilter(settings.frameEffect);x.fillStyle=pattern;x.fillRect(0,0,w,h);x.restore()}}
function shapePath(x:CanvasRenderingContext2D,s:Slot,shape:BoothSettings['photoShape']){x.beginPath();if(shape==='circle'){x.ellipse(s.x+s.w/2,s.y+s.h/2,s.w/2,s.h/2,0,0,Math.PI*2);return}if(shape==='rounded'){x.roundRect(s.x,s.y,s.w,s.h,Math.min(s.w,s.h)*.12);return}if(shape==='arch'){x.moveTo(s.x,s.y+s.h);x.lineTo(s.x,s.y+s.w/2);x.arc(s.x+s.w/2,s.y+s.w/2,s.w/2,Math.PI,0);x.lineTo(s.x+s.w,s.y+s.h);x.closePath();return}if(shape==='heart'){const cx=s.x+s.w/2,top=s.y+s.h*.22;x.moveTo(cx,s.y+s.h*.9);x.bezierCurveTo(s.x-s.w*.05,s.y+s.h*.55,s.x,s.y+s.h*.1,cx,top);x.bezierCurveTo(s.x+s.w,s.y+s.h*.1,s.x+s.w*1.05,s.y+s.h*.55,cx,s.y+s.h*.9);x.closePath();return}x.rect(s.x,s.y,s.w,s.h)}
const inkFor=(color:string)=>{const h=color.replace('#','');if(h.length!==6)return'#33282c';const lum=(parseInt(h.slice(0,2),16)*299+parseInt(h.slice(2,4),16)*587+parseInt(h.slice(4,6),16)*114)/1000;return lum<125?'#fffafc':'#352a2e'};
const heart=(x:CanvasRenderingContext2D,cx:number,cy:number,size:number)=>{x.save();x.translate(cx,cy);x.beginPath();x.moveTo(0,size*.3);x.bezierCurveTo(-size,-size*.25,-size*.55,-size,0,-size*.45);x.bezierCurveTo(size*.55,-size,size,-size*.25,0,size*.3);x.fill();x.restore()};
function decoration(x:CanvasRenderingContext2D,layout:BoothLayout,settings:BoothSettings){const ink=settings.textColor||inkFor(settings.frame),title=settings.titleText||settings.caption||'forever, us',footer=settings.footerText||'made with petal booth',date=settings.dateText||new Date().toLocaleDateString();x.fillStyle=ink;x.strokeStyle=ink;x.textAlign='center';x.globalAlpha=.9;const titleFont=settings.fontStyle==='clean'?'800 44px system-ui':settings.fontStyle==='editorial'?'600 44px Georgia':'italic 600 48px Georgia';
 if(layout.id.startsWith('paired-')){x.font=titleFont;x.fillText(title,layout.width/2,68);x.font='500 18px system-ui';x.fillText(`${date}  ·  ${footer}`,layout.width/2,layout.height-48)}
 if(layout.id==='strip-3'){x.font='600 16px system-ui';x.letterSpacing='3px';x.fillText(date,layout.width/2,55);x.font=titleFont;x.letterSpacing='0px';x.fillText(title,layout.width/2,layout.height-150);x.font='500 17px system-ui';x.fillText(footer,layout.width/2,layout.height-104)}
 if(layout.id==='strip-4'){x.font='600 15px system-ui';x.fillText(date,layout.width/2,42);x.beginPath();x.moveTo(70,layout.height-122);x.lineTo(layout.width-70,layout.height-122);x.stroke();x.font=titleFont;x.fillText(title,layout.width/2,layout.height-73);x.font='500 16px system-ui';x.fillText(footer,layout.width/2,layout.height-40)}
 if(layout.id==='strip-2'){x.font=titleFont;x.fillText(title,layout.width/2,76);x.font='500 16px system-ui';x.letterSpacing='3px';x.fillText(date,layout.width/2,108);x.letterSpacing='0px';x.font='600 22px system-ui';x.fillText(footer,layout.width/2,layout.height-107)}
 if(layout.id==='grid-4'){x.textAlign='left';x.font=titleFont;x.fillText(title,48,76);x.textAlign='right';x.font='500 18px system-ui';x.fillText(date,layout.width-48,72);x.textAlign='center';x.font='600 24px system-ui';x.fillText(footer,layout.width/2,layout.height-85)}
 if(layout.id==='grid-6'){x.textAlign='left';x.font=titleFont;x.fillText(title,55,72);x.textAlign='right';x.font='500 18px system-ui';x.fillText(date,layout.width-55,68);x.textAlign='center';x.font='600 22px system-ui';x.fillText(footer,layout.width/2,layout.height-70)}
 if(layout.id==='single'){x.font='500 18px system-ui';x.letterSpacing='4px';x.fillText(date,layout.width/2,82);x.font=titleFont;x.letterSpacing='0px';x.fillText(title,layout.width/2,layout.height-142);x.font='600 20px system-ui';x.fillText(footer,layout.width/2,layout.height-94)}
 if(layout.id==='album-square'){x.font='600 20px system-ui';x.letterSpacing='5px';x.fillText(date,layout.width/2,100);x.font='italic 700 62px Georgia';x.letterSpacing='0px';x.fillText(title,layout.width/2,layout.height-128);x.font='600 20px system-ui';x.fillText(footer,layout.width/2,layout.height-78)}x.letterSpacing='0px';x.globalAlpha=1}

export async function compose(layout:BoothLayout,photos:string[],settings:BoothSettings,crops:CropState[]){const canvas=document.createElement('canvas');canvas.width=layout.width;canvas.height=layout.height;const x=canvas.getContext('2d')!;await frameFill(x,canvas.width,canvas.height,settings);const slots=getSlots(layout,settings.gap);
  for(let i=0;i<slots.length;i++){const s=slots[i];x.save();shapePath(x,s,settings.photoShape);x.clip();x.fillStyle=settings.background;x.fillRect(s.x,s.y,s.w,s.h);if(photos[i]){const im=await load(photos[i]);const crop=crops[i]||{zoom:1,x:0,y:0,brightness:100,contrast:100,filter:'none'};const scale=Math.max(s.w/im.width,s.h/im.height)*crop.zoom,dw=im.width*scale,dh=im.height*scale;const tones:Record<string,string>={none:'none',mono:'grayscale(1) contrast(1.08)',warm:'sepia(.28) saturate(1.2)',vintage:'sepia(.55) contrast(.9)',cinematic:'contrast(1.22) saturate(.82) hue-rotate(-8deg)',grainy:'contrast(1.12) saturate(.9)',cool:'saturate(.9) hue-rotate(12deg)',fade:'contrast(.82) brightness(1.08) saturate(.72)'};x.filter=`brightness(${crop.brightness}%) contrast(${crop.contrast}%) ${tones[crop.filter]||'none'}`;x.drawImage(im,s.x+(s.w-dw)/2+crop.x,s.y+(s.h-dh)/2+crop.y,dw,dh);if(crop.filter==='grainy'){x.globalAlpha=.13;x.fillStyle='#fff';for(let n=0;n<1400;n++){const px=s.x+((n*73)%Math.max(1,Math.floor(s.w))),py=s.y+((n*151)%Math.max(1,Math.floor(s.h)));x.fillRect(px,py,(n%3)+1,(n%3)+1)}x.globalAlpha=1}}x.restore()}
  decoration(x,layout,settings);const chosen=settings.stickers||[];if(chosen.length){const top=Math.min(...slots.map(s=>s.y)),bottom=Math.max(...slots.map(s=>s.y+s.h)),topSize=Math.max(30,Math.min(86,top*.58)),bottomSize=Math.max(30,Math.min(86,(layout.height-bottom)*.38)),topY=Math.max(topSize/2+5,top/2),bottomY=Math.min(layout.height-bottomSize/2-5,bottom+(layout.height-bottom)/2);const zoneSpots={"top-left":{x:50,y:topY,s:topSize},"top-center":{x:layout.width/2,y:topY,s:topSize},"top-right":{x:layout.width-50,y:topY,s:topSize},"bottom-left":{x:50,y:bottomY,s:bottomSize},"bottom-center":{x:layout.width/2,y:bottomY,s:bottomSize},"bottom-right":{x:layout.width-50,y:bottomY,s:bottomSize}} as const;for(let i=0;i<Math.min(chosen.length,6);i++){const item=chosen[i],fallback=Object.keys(zoneSpots)[i] as keyof typeof zoneSpots,placement=settings.decorationPlacements?.[item]||{zone:fallback,scale:1,rotation:0},spot=zoneSpots[placement.zone],size=spot.s*placement.scale;x.save();x.translate(spot.x,spot.y);x.rotate(placement.rotation*Math.PI/180);if(item.startsWith('/')){const asset=await load(item);x.drawImage(asset,-size/2,-size/2,size,size)}else{x.font=`${size}px Apple Color Emoji, sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillText(item,0,0)}x.restore()}}return canvas;
}
