import {Camera,FlipHorizontal2,RefreshCw,RotateCcw,SwitchCamera,WandSparkles,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import type {BoothLayout,BoothSettings} from '../types';
import {useCamera} from '../hooks/useCamera';

type CameraLens={id:string;name:string;filter:string;overlay?:'hearts'|'flower'|'puppy'};
const CAMERA_LENSES:CameraLens[]=[
  {id:'none',name:'Original',filter:'none'},
  {id:'glow',name:'Soft glow',filter:'brightness(1.08) contrast(.94) saturate(1.08)'},
  {id:'rosy',name:'Rosy',filter:'brightness(1.05) contrast(.96) saturate(1.28) sepia(.08) hue-rotate(-8deg)'},
  {id:'dream',name:'Dreamy',filter:'brightness(1.12) contrast(.86) saturate(.88) sepia(.12)'},
  {id:'cool',name:'Cool',filter:'brightness(1.03) contrast(1.04) saturate(.9) hue-rotate(12deg)'},
  {id:'mono',name:'B&W',filter:'grayscale(1) contrast(1.12)'},
  {id:'hearts',name:'Hearts',filter:'brightness(1.06) saturate(1.12)',overlay:'hearts'},
  {id:'flower',name:'Flower crown',filter:'brightness(1.05) saturate(1.16)',overlay:'flower'},
  {id:'puppy',name:'Puppy',filter:'brightness(1.04) saturate(1.08)',overlay:'puppy'},
];

function LensOverlay({kind}:{kind?:CameraLens['overlay']}){if(!kind)return null;if(kind==='hearts')return <div className="lens-overlay lens-hearts" aria-hidden><span>💗</span><span>💕</span><span>💖</span><span>💗</span></div>;if(kind==='flower')return <div className="lens-overlay lens-flower" aria-hidden>🌼 🌸 🌺 🌸 🌼</div>;return <div className="lens-overlay lens-puppy" aria-hidden><span>🐶</span><i/></div>}
function drawLensOverlay(x:CanvasRenderingContext2D,w:number,h:number,kind?:CameraLens['overlay']){if(!kind)return;x.save();x.textAlign='center';x.textBaseline='middle';const emoji=(text:string,px:number,py:number,size:number)=>{x.font=`${size}px Apple Color Emoji, Segoe UI Emoji, sans-serif`;x.fillText(text,px,py)};if(kind==='hearts'){emoji('💗',w*.25,h*.28,h*.12);emoji('💕',w*.72,h*.22,h*.13);emoji('💖',w*.8,h*.46,h*.1);emoji('💗',w*.18,h*.52,h*.09)}if(kind==='flower')emoji('🌼 🌸 🌺 🌸 🌼',w*.5,h*.18,h*.105);if(kind==='puppy'){emoji('🐶',w*.5,h*.22,h*.28);x.fillStyle='#2a1814';x.beginPath();x.arc(w*.5,h*.51,h*.035,0,Math.PI*2);x.fill()}x.restore()}

export function CameraBooth({layout,settings,onDone,onExit}:{layout:BoothLayout;settings:BoothSettings;onDone:(p:string[])=>void;onExit:()=>void}){
  const cam=useCamera(),video=useRef<HTMLVideoElement>(null),completed=useRef(false);
  const [photos,setPhotos]=useState<string[]>([]),[count,setCount]=useState<number|null>(null),[flash,setFlash]=useState(false),[delay,setDelay]=useState<3|5|10>(settings.countdown),[inverted,setInverted]=useState(true),[lensId,setLensId]=useState('none');
  const lens=CAMERA_LENSES.find(item=>item.id===lensId)??CAMERA_LENSES[0];
  useEffect(()=>{if(video.current&&cam.stream.current)video.current.srcObject=cam.stream.current},[cam.status,cam.stream]);
  const capture=async()=>{if(count!==null||cam.status!=='ready'||completed.current)return;const end=Date.now()+delay*1000;setCount(delay);await new Promise<void>(resolve=>{const timer=window.setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setCount(left);if(Date.now()>=end){clearInterval(timer);resolve()}},60)});const v=video.current;if(!v||!v.videoWidth){setCount(null);return}const maxWidth=1600,scale=Math.min(1,maxWidth/v.videoWidth),c=document.createElement('canvas');c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);const x=c.getContext('2d')!;x.save();if(inverted){x.translate(c.width,0);x.scale(-1,1)}x.filter=lens.filter;x.drawImage(v,0,0,c.width,c.height);x.restore();drawLensOverlay(x,c.width,c.height,lens.overlay);const image=c.toDataURL('image/jpeg',.9);setFlash(true);window.setTimeout(()=>setFlash(false),220);setCount(null);setPhotos(previous=>{const next=[...previous,image];if(next.length>=layout.poses&&!completed.current){completed.current=true;queueMicrotask(()=>onDone(next.slice(0,layout.poses)))}return next})};
  return <main className="booth-page"><div className="booth-top"><button className="text-button" onClick={()=>{cam.stop();onExit()}}><X size={18}/> Exit session</button><span aria-live="polite">Photo {Math.min(photos.length+1,layout.poses)} of {layout.poses}</span></div><section className="camera-shell">{cam.status!=='ready'?<div className="permission"><div className="camera-icon"><Camera/></div><h1>Ready when you are</h1><p>We only turn on your camera after you press the button. Nothing is uploaded or stored.</p>{cam.status==='error'&&<div className="error" role="alert">{cam.error}</div>}<button className="primary" disabled={cam.status==='loading'} onClick={()=>cam.start()}>{cam.status==='loading'?'Opening camera…':'Allow camera access'}</button></div>:<><video ref={video} autoPlay playsInline muted className={inverted?'mirror':''} style={{filter:lens.filter}}/><LensOverlay kind={lens.overlay}/>{count!==null&&<div className="countdown" aria-live="assertive">{count||<Camera/>}</div>}{flash&&<div className="flash"/>}<div className="camera-controls"><button onClick={cam.switchCamera} aria-label="Switch front or rear camera"><SwitchCamera/></button><button className="shutter" onClick={capture} disabled={count!==null} aria-label="Take photo"><span/></button><button disabled={!photos.length} onClick={()=>setPhotos(p=>p.slice(0,-1))} aria-label="Retake latest photo"><RotateCcw/></button></div></>}</section><section className="camera-lenses" aria-label="Camera filters"><div className="lens-title"><WandSparkles size={16}/><span>Filters</span><strong>{lens.name}</strong></div><div className="lens-list">{CAMERA_LENSES.map(item=><button key={item.id} className={lensId===item.id?'active':''} onClick={()=>setLensId(item.id)} aria-pressed={lensId===item.id}><span className={`lens-swatch lens-swatch-${item.id}`} style={{filter:item.filter}}>{item.overlay==='hearts'?'💗':item.overlay==='flower'?'🌸':item.overlay==='puppy'?'🐶':'☺'}</span><small>{item.name}</small></button>)}</div></section><div className="capture-options"><div className="count-options"><span>Countdown</span>{([3,5,10] as const).map(n=><button className={delay===n?'active':''} onClick={()=>setDelay(n)} key={n}>{n}s</button>)}</div><button className={`mirror-toggle ${inverted?'active':''}`} onClick={()=>setInverted(v=>!v)} aria-pressed={inverted}><FlipHorizontal2 size={17}/> Inverted result: {inverted?'On':'Off'}</button></div><p className="capture-help">The saved photo will match this preview, including your selected filter.</p>{photos.length>0&&<div className="capture-tray">{photos.map((p,i)=><img src={p} alt={`Captured pose ${i+1}`} key={i}/>) }<button onClick={()=>setPhotos([])}><RefreshCw size={15}/> Restart</button></div>}</main>;
}
