import {Camera,FlipHorizontal2,RefreshCw,RotateCcw,SwitchCamera,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import type {BoothLayout,BoothSettings} from '../types';
import {useCamera} from '../hooks/useCamera';

export function CameraBooth({layout,settings,onDone,onExit}:{layout:BoothLayout;settings:BoothSettings;onDone:(p:string[])=>void;onExit:()=>void}){
  const cam=useCamera(),video=useRef<HTMLVideoElement>(null);
  const [photos,setPhotos]=useState<string[]>([]),[count,setCount]=useState<number|null>(null),[flash,setFlash]=useState(false),[delay,setDelay]=useState<3|5|10>(settings.countdown),[inverted,setInverted]=useState(true);
  useEffect(()=>{if(video.current&&cam.stream.current)video.current.srcObject=cam.stream.current},[cam.status,cam.stream]);
  const capture=async()=>{if(count!==null||cam.status!=='ready')return;const end=Date.now()+delay*1000;setCount(delay);await new Promise<void>(resolve=>{const timer=window.setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setCount(left);if(Date.now()>=end){clearInterval(timer);resolve()}},60)});const v=video.current;if(!v||!v.videoWidth){setCount(null);return}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d')!;if(inverted){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(v,0,0);setFlash(true);window.setTimeout(()=>setFlash(false),220);const next=[...photos,c.toDataURL('image/jpeg',.96)];setPhotos(next);setCount(null);if(next.length===layout.poses){cam.stop();onDone(next)}};
  return <main className="booth-page"><div className="booth-top"><button className="text-button" onClick={()=>{cam.stop();onExit()}}><X size={18}/> Exit session</button><span aria-live="polite">Photo {Math.min(photos.length+1,layout.poses)} of {layout.poses}</span></div><section className="camera-shell">{cam.status!=='ready'?<div className="permission"><div className="camera-icon"><Camera/></div><h1>Ready when you are</h1><p>We only turn on your camera after you press the button. Nothing is uploaded or stored.</p>{cam.status==='error'&&<div className="error" role="alert">{cam.error}</div>}<button className="primary" disabled={cam.status==='loading'} onClick={()=>cam.start()}>{cam.status==='loading'?'Opening camera…':'Allow camera access'}</button></div>:<><video ref={video} autoPlay playsInline muted className={inverted?'mirror':''}/>{count!==null&&<div className="countdown" aria-live="assertive">{count||<Camera/>}</div>}{flash&&<div className="flash"/>}<div className="camera-controls"><button onClick={cam.switchCamera} aria-label="Switch front or rear camera"><SwitchCamera/></button><button className="shutter" onClick={capture} disabled={count!==null} aria-label="Take photo"><span/></button><button disabled={!photos.length} onClick={()=>setPhotos(p=>p.slice(0,-1))} aria-label="Retake latest photo"><RotateCcw/></button></div></>}</section><div className="capture-options"><div className="count-options"><span>Countdown</span>{([3,5,10] as const).map(n=><button className={delay===n?'active':''} onClick={()=>setDelay(n)} key={n}>{n}s</button>)}</div><button className={`mirror-toggle ${inverted?'active':''}`} onClick={()=>setInverted(v=>!v)} aria-pressed={inverted}><FlipHorizontal2 size={17}/> Inverted result: {inverted?'On':'Off'}</button></div><p className="capture-help">The saved photo will match this preview exactly.</p>{photos.length>0&&<div className="capture-tray">{photos.map((p,i)=><img src={p} alt={`Captured pose ${i+1}`} key={i}/>) }<button onClick={()=>setPhotos([])}><RefreshCw size={15}/> Restart</button></div>}</main>;
}
