import {Palette,Sparkles,Type} from 'lucide-react';
import {useState} from 'react';
import {FRAME_EFFECTS,FRAME_STYLES,PALETTES,PHOTO_SHAPES,STICKERS} from '../data/customization';
import {LAYOUTS} from '../data/layouts';
import type {BoothLayout,BoothSettings,DecorationPlacement,DecorationZone,FilterName} from '../types';
import {LayoutPreview} from './LayoutPreview';

const ZONES:{id:DecorationZone;label:string}[]=[{id:'top-left',label:'↖'},{id:'top-center',label:'↑'},{id:'top-right',label:'↗'},{id:'bottom-left',label:'↙'},{id:'bottom-center',label:'↓'},{id:'bottom-right',label:'↘'}];
const ALBUM_IDS=new Set(['arctic-monkeys','1989','portrait-noir','ocean-blue','fearless-tv','blonde','silk-sonic','after-hours','1975-self-titled','reputation','the-1975','folklore']);
const PHOTO_FILTERS:FilterName[]=['none','cinematic','grainy','warm','vintage','mono','cool','fade'];

export function CustomizationPanel({layout,settings,onLayout,onChange,allowLayout=true}:{layout:BoothLayout;settings:BoothSettings;onLayout:(layout:BoothLayout)=>void;onChange:(settings:BoothSettings)=>void;allowLayout?:boolean}){
 const [active,setActive]=useState(''),chosen=settings.stickers||[],albumMode=layout.id==='album-square',materials=FRAME_STYLES.filter(item=>albumMode?ALBUM_IDS.has(item.id):!ALBUM_IDS.has(item.id));
 const selectLayout=(item:BoothLayout)=>{if(item.id!=='album-square'&&settings.frameStyle&&ALBUM_IDS.has(settings.frameStyle))onChange({...settings,frameStyle:'solid'});if(item.id==='album-square'&&(!settings.frameStyle||!ALBUM_IDS.has(settings.frameStyle)))onChange({...settings,frameStyle:'arctic-monkeys',photoShape:'square'});onLayout(item)};
 const toggle=(value:string)=>{const has=chosen.includes(value);if(!has&&chosen.length>=6)return;const next=has?chosen.filter(item=>item!==value):[...chosen,value],placements={...(settings.decorationPlacements||{})};if(has)delete placements[value];else placements[value]={zone:ZONES[chosen.length].id,scale:1,rotation:0};onChange({...settings,stickers:next,decorationPlacements:placements});setActive(has?'':value)};
 const placement=active?settings.decorationPlacements?.[active]:undefined,place=(patch:Partial<DecorationPlacement>)=>placement&&onChange({...settings,decorationPlacements:{...(settings.decorationPlacements||{}),[active]:{...placement,...patch}}});
 return <section className="post-designer"><div className="post-preview"><span className="eyebrow">LIVE DESIGN</span><LayoutPreview layout={layout} settings={settings}/><strong>{layout.name}</strong></div><div className="post-controls"><div className="studio-title"><div><span className="eyebrow">EDIT AFTER CAPTURE</span><h2>Design your keepsake</h2></div><Sparkles/></div>
 {allowLayout&&!settings.layoutLocked&&<fieldset><legend>Layout</legend><div className="post-layouts">{LAYOUTS.map(item=><button className={layout.id===item.id?'active':''} onClick={()=>selectLayout(item)} key={item.id}><LayoutPreview layout={item}/><span>{item.name}</span></button>)}</div></fieldset>}
 <fieldset><legend><Type size={16}/> Text and typography</legend><div className="text-editor"><label>Main title<input value={settings.titleText||''} maxLength={32} onChange={event=>onChange({...settings,titleText:event.target.value})}/></label><label>Footer<input value={settings.footerText||''} maxLength={42} onChange={event=>onChange({...settings,footerText:event.target.value})}/></label><label>Date / short line<input value={settings.dateText||''} maxLength={24} onChange={event=>onChange({...settings,dateText:event.target.value})}/></label><label>Text color<input type="color" value={settings.textColor||'#352a2e'} onChange={event=>onChange({...settings,textColor:event.target.value})}/></label></div><div className="font-grid">{(['script','signature','fashion','editorial','clean'] as const).map(font=><button className={settings.fontStyle===font?'active':''} onClick={()=>onChange({...settings,fontStyle:font})} key={font}>{font}</button>)}</div></fieldset>
 <fieldset><legend><Palette size={16}/> {albumMode?'Album artwork':'Frame material and color'}</legend>{!albumMode&&<div className="swatch-grid">{PALETTES.map(color=><button className={settings.frame===color?'active':''} style={{background:color}} onClick={()=>onChange({...settings,frame:color})} aria-label={`Use frame color ${color}`} key={color}/>)}</div>}<div className="pattern-grid">{materials.map(item=><button className={settings.frameStyle===item.id?'active':''} onClick={()=>onChange({...settings,frameStyle:item.id})} key={item.id}><i style={{background:item.css}}/><span>{item.name}</span></button>)}</div>{albumMode&&<p className="control-help">Album artwork is exclusive to this square cover format.</p>}</fieldset>
 <fieldset><legend>Photo filter</legend><div className="effect-grid photo-filter-grid">{PHOTO_FILTERS.map(filter=><button className={(settings.photoFilter||'none')===filter?'active':''} onClick={()=>onChange({...settings,photoFilter:filter})} key={filter}>{filter}</button>)}</div></fieldset>
 {settings.layoutLocked&&<fieldset><legend>Two-strip background</legend><div className="output-background-grid"><button className={(settings.outputBackground||'transparent')==='transparent'?'active':''} onClick={()=>onChange({...settings,outputBackground:'transparent'})}><span className="alpha-swatch"/>Transparent PNG</button><button className={settings.outputBackground==='white'?'active':''} onClick={()=>onChange({...settings,outputBackground:'white'})}><span className="white-swatch"/>White background</button></div></fieldset>}
 <fieldset><legend>Frame effect</legend><div className="effect-grid">{FRAME_EFFECTS.map(effect=><button className={(settings.frameEffect||'natural')===effect.id?'active':''} onClick={()=>onChange({...settings,frameEffect:effect.id})} key={effect.id}>{effect.name}</button>)}</div></fieldset>
 <fieldset><legend>Photo shape</legend><div className="shape-grid">{PHOTO_SHAPES.map(shape=><button className={settings.photoShape===shape.id?'active':''} onClick={()=>onChange({...settings,photoShape:shape.id})} key={shape.id}><b>{shape.symbol}</b><span>{shape.name}</span></button>)}</div></fieldset>
 <fieldset><legend>Decorations <small>{chosen.length}/6</small></legend><div className="sticker-grid">{STICKERS.map(item=><button className={chosen.includes(item.value)?'active':''} onClick={()=>toggle(item.value)} key={item.name}>{item.value.startsWith('/')?<img src={item.value} alt={item.name}/>:item.value}</button>)}</div></fieldset>
 {chosen.length>0&&<fieldset className="decoration-editor"><legend>Place decorations in safe frame zones</legend><div className="decoration-tabs">{chosen.map(item=><button className={active===item?'active':''} onClick={()=>setActive(item)} key={item}>{item.startsWith('/')?<img src={item} alt=""/>:item}</button>)}</div>{placement&&<><div className="zone-grid">{ZONES.map(zone=><button className={placement.zone===zone.id?'active':''} onClick={()=>place({zone:zone.id})} key={zone.id}>{zone.label}</button>)}</div><div className="placement-sliders"><label>Size<input type="range" min=".65" max="1.65" step=".05" value={placement.scale} onChange={event=>place({scale:+event.target.value})}/></label><label>Rotation<input type="range" min="-35" max="35" value={placement.rotation} onChange={event=>place({rotation:+event.target.value})}/></label></div></>}</fieldset>}
 </div></section>;
}
