import {Construction,Palette,Sparkles,Type} from 'lucide-react';
import {FRAME_EFFECTS,FRAME_STYLES,PALETTES,PHOTO_SHAPES} from '../data/customization';
import type {BoothLayout,BoothSettings,FilterName} from '../types';
import {LayoutPreview} from './LayoutPreview';

const ALBUM_IDS=new Set(['arctic-monkeys','1989','portrait-noir','ocean-blue','fearless-tv','blonde','silk-sonic','after-hours','1975-self-titled','reputation','the-1975','folklore']);
const PHOTO_FILTERS:FilterName[]=['none','cinematic','grainy','warm','vintage','mono','cool','fade'];

export function CustomizationPanel({layout,settings,onChange}:{layout:BoothLayout;settings:BoothSettings;onChange:(settings:BoothSettings)=>void}){
 const albumMode=layout.id==='album-square',materials=FRAME_STYLES.filter(item=>albumMode?ALBUM_IDS.has(item.id):!ALBUM_IDS.has(item.id));
 return <section className="post-designer"><div className="post-preview"><span className="eyebrow">LIVE DESIGN</span><LayoutPreview layout={layout} settings={settings}/><strong>{layout.name}</strong></div><div className="post-controls"><div className="studio-title"><div><span className="eyebrow">EDIT AFTER CAPTURE</span><h2>Design your keepsake</h2></div><Sparkles/></div>
 <fieldset><legend><Type size={16}/> Text and typography</legend><div className="text-editor"><label>Main title<input value={settings.titleText||''} maxLength={32} onChange={event=>onChange({...settings,titleText:event.target.value})}/></label><label>Footer<input value={settings.footerText||''} maxLength={42} onChange={event=>onChange({...settings,footerText:event.target.value})}/></label><label>Date / short line<input value={settings.dateText||''} maxLength={24} onChange={event=>onChange({...settings,dateText:event.target.value})}/></label><label>Text color<input type="color" value={settings.textColor||'#352a2e'} onChange={event=>onChange({...settings,textColor:event.target.value})}/></label></div><div className="font-grid">{(['script','signature','fashion','editorial','clean'] as const).map(font=><button className={settings.fontStyle===font?'active':''} onClick={()=>onChange({...settings,fontStyle:font})} key={font}>{font}</button>)}</div></fieldset>
 <fieldset><legend><Palette size={16}/> {albumMode?'Album artwork':'Frame material and color'}</legend>{!albumMode&&<div className="swatch-grid">{PALETTES.map(color=><button className={settings.frame===color?'active':''} style={{background:color}} onClick={()=>onChange({...settings,frame:color})} aria-label={`Use frame color ${color}`} key={color}/>)}</div>}<div className="pattern-grid">{materials.map(item=><button className={settings.frameStyle===item.id?'active':''} onClick={()=>onChange({...settings,frameStyle:item.id})} key={item.id}><i style={{background:item.css}}/><span>{item.name}</span></button>)}</div>{albumMode&&<p className="control-help">Album artwork is exclusive to this square cover format.</p>}</fieldset>
 <fieldset><legend>Photo filter</legend><div className="effect-grid photo-filter-grid">{PHOTO_FILTERS.map(filter=><button className={(settings.photoFilter||'none')===filter?'active':''} onClick={()=>onChange({...settings,photoFilter:filter})} key={filter}>{filter}</button>)}</div></fieldset>
 {settings.layoutLocked&&<fieldset><legend>Two-strip background</legend><div className="output-background-grid"><button className={(settings.outputBackground||'transparent')==='transparent'?'active':''} onClick={()=>onChange({...settings,outputBackground:'transparent'})}><span className="alpha-swatch"/>Transparent PNG</button><button className={settings.outputBackground==='white'?'active':''} onClick={()=>onChange({...settings,outputBackground:'white'})}><span className="white-swatch"/>White background</button></div></fieldset>}
 <fieldset><legend>Frame effect</legend><div className="effect-grid">{FRAME_EFFECTS.map(effect=><button className={(settings.frameEffect||'natural')===effect.id?'active':''} onClick={()=>onChange({...settings,frameEffect:effect.id})} key={effect.id}>{effect.name}</button>)}</div></fieldset>
 <fieldset><legend>Photo shape</legend><div className="shape-grid">{PHOTO_SHAPES.map(shape=><button className={settings.photoShape===shape.id?'active':''} onClick={()=>onChange({...settings,photoShape:shape.id})} key={shape.id}><b>{shape.symbol}</b><span>{shape.name}</span></button>)}</div></fieldset>
 <fieldset><legend><Construction size={16}/> Stickers</legend><div className="development-note" role="note"><Construction size={18}/><div><strong>Currently in development</strong><p>Stickers are temporarily unavailable while we improve placement and export quality.</p></div></div></fieldset>
 </div></section>;
}
