import {ArrowLeft,ArrowRight,Check,Palette,Sparkles,Shapes,Type} from 'lucide-react';import {useEffect,useRef,useState} from 'react';import {LAYOUTS} from '../data/layouts';import {FRAME_EFFECTS,FRAME_STYLES,PALETTES,PHOTO_SHAPES,STICKERS} from '../data/customization';import type {BoothLayout,BoothSettings,DecorationPlacement,DecorationZone} from '../types';import {LayoutPreview} from './LayoutPreview';
const ZONES:{id:DecorationZone;label:string}[]=[{id:'top-left',label:'↖ Top left'},{id:'top-center',label:'↑ Top'},{id:'top-right',label:'↗ Top right'},{id:'bottom-left',label:'↙ Bottom left'},{id:'bottom-center',label:'↓ Bottom'},{id:'bottom-right',label:'↘ Bottom right'}];
export function LayoutGallery({selected,onSelect,settings,setSettings,onContinue}:{selected:BoothLayout;onSelect:(l:BoothLayout)=>void;settings:BoothSettings;setSettings:(s:BoothSettings)=>void;onContinue:()=>void}){
 const rail=useRef<HTMLDivElement>(null),chosen=settings.stickers||[];const [activeDecoration,setActiveDecoration]=useState('');const move=(n:number)=>rail.current?.scrollBy({left:n*310,behavior:'smooth'});useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 const toggleSticker=(value:string)=>{const exists=chosen.includes(value);if(!exists&&chosen.length>=6)return;const next=exists?chosen.filter(v=>v!==value):[...chosen,value],placements={...(settings.decorationPlacements||{})};if(!exists)placements[value]={zone:ZONES[chosen.length].id,scale:1,rotation:0};else delete placements[value];setSettings({...settings,stickers:next,decorationPlacements:placements});setActiveDecoration(exists?'':value)};
 const updatePlacement=(patch:Partial<DecorationPlacement>)=>{if(!activeDecoration)return;const current=settings.decorationPlacements?.[activeDecoration]||{zone:'top-left',scale:1,rotation:0};setSettings({...settings,decorationPlacements:{...(settings.decorationPlacements||{}),[activeDecoration]:{...current,...patch}}})};const activePlacement=activeDecoration?settings.decorationPlacements?.[activeDecoration]:undefined;
 return <main className="gallery-page"><div className="eyebrow">STEP 01 — PICK YOUR FAVORITE</div><h1>Choose your layout</h1><p className="lead">Six art-directed designs, ready to make completely yours.</p><div className="gallery-wrap"><button className="round-arrow left" onClick={()=>move(-1)} aria-label="Previous layouts"><ArrowLeft/></button><div className="layout-rail" ref={rail}>{LAYOUTS.map((l,i)=><button className={`layout-card ${selected.id===l.id?'selected':''}`} onClick={()=>onSelect(l)} key={l.id}><div className="card-number">{String(i+1).padStart(2,'0')}</div><LayoutPreview layout={l} settings={settings}/><h3>{l.name}</h3><p>{l.description}</p><span>{l.poses} {l.poses===1?'pose':'poses'}</span>{selected.id===l.id&&<i><Check size={15}/> selected</i>}</button>)}</div><button className="round-arrow right" onClick={()=>move(1)} aria-label="Next layouts"><ArrowRight/></button></div>
 <section className="custom-studio"><div className="studio-preview"><span className="eyebrow">LIVE PREVIEW</span><LayoutPreview layout={selected} settings={settings}/><h3>{selected.name}</h3><p>Every text, effect and decoration placement is included in your HD export.</p></div><div className="studio-controls"><div className="studio-title"><div><span className="eyebrow">STEP 02 — MAKE IT YOURS</span><h2>Customize your photo</h2></div><Sparkles/></div>
 <fieldset><legend><Type size={17}/> Layout text</legend><div className="text-editor"><label className="wide">Main title<input maxLength={32} value={settings.titleText||''} onChange={e=>setSettings({...settings,titleText:e.target.value})}/></label><label>Footer text<input maxLength={42} value={settings.footerText||''} onChange={e=>setSettings({...settings,footerText:e.target.value})}/></label><label>Date or short line<input maxLength={24} value={settings.dateText||''} onChange={e=>setSettings({...settings,dateText:e.target.value})}/></label><label>Text color<input type="color" value={settings.textColor||'#352a2e'} onChange={e=>setSettings({...settings,textColor:e.target.value})}/></label></div><div className="font-grid">{(['script','editorial','clean'] as const).map(font=><button className={settings.fontStyle===font?'active':''} onClick={()=>setSettings({...settings,fontStyle:font})} key={font}>{font}</button>)}</div></fieldset>
 <fieldset><legend><Palette size={17}/> Material color</legend><p className="control-help">Tint the material without losing its texture and highlights.</p><div className="swatch-grid">{PALETTES.map(color=><button className={settings.frame===color?'active':''} style={{background:color}} onClick={()=>setSettings({...settings,frame:color})} aria-label={`Use material color ${color}`} key={color}/>) }<label className="color-picker" title="Custom color"><input type="color" value={settings.frame} onChange={e=>setSettings({...settings,frame:e.target.value})}/><span>+</span></label></div></fieldset>
 <fieldset><legend><Sparkles size={17}/> HD frame material</legend><div className="pattern-grid">{FRAME_STYLES.map(item=><button className={settings.frameStyle===item.id?'active':''} onClick={()=>setSettings({...settings,frameStyle:item.id})} title={item.name} aria-label={`Use ${item.name} frame`} key={item.id}><i style={{background:item.css}}/><span>{item.name}</span></button>)}</div></fieldset>
 <fieldset><legend>Frame effect</legend><div className="effect-grid">{FRAME_EFFECTS.map(effect=><button className={(settings.frameEffect||'natural')===effect.id?'active':''} onClick={()=>setSettings({...settings,frameEffect:effect.id})} key={effect.id}>{effect.name}</button>)}</div></fieldset>
 <fieldset><legend><Shapes size={17}/> Photo shape</legend><div className="shape-grid">{PHOTO_SHAPES.map(shape=><button className={settings.photoShape===shape.id?'active':''} onClick={()=>setSettings({...settings,photoShape:shape.id})} key={shape.id}><b>{shape.symbol}</b><span>{shape.name}</span></button>)}</div></fieldset>
 <fieldset><legend>Decorations <small>{chosen.length}/6 selected</small></legend><p className="control-help">Add up to six, then choose one below to move, resize, or rotate it in safe frame areas.</p><div className="sticker-grid"><button className={!chosen.length?'active':''} onClick={()=>{setSettings({...settings,stickers:[],decorationPlacements:{}});setActiveDecoration('')}} aria-label="Remove all decorations">∅</button>{STICKERS.map(item=><button className={chosen.includes(item.value)?'active':''} onClick={()=>toggleSticker(item.value)} title={item.name} aria-label={`Decoration: ${item.name}`} key={item.name}>{item.value.startsWith('/')?<img src={item.value} alt=""/>:item.value}</button>)}</div></fieldset>
 {chosen.length>0&&<fieldset className="decoration-editor"><legend>Arrange decorations</legend><div className="decoration-tabs">{chosen.map(item=><button className={activeDecoration===item?'active':''} onClick={()=>setActiveDecoration(item)} aria-label="Select decoration to arrange" key={item}>{item.startsWith('/')?<img src={item} alt=""/>:item}</button>)}</div>{activeDecoration&&activePlacement&&<><div className="zone-grid">{ZONES.map(zone=><button className={activePlacement.zone===zone.id?'active':''} onClick={()=>updatePlacement({zone:zone.id})} key={zone.id}>{zone.label}</button>)}</div><div className="placement-sliders"><label>Size<input type="range" min="0.65" max="1.65" step="0.05" value={activePlacement.scale} onChange={e=>updatePlacement({scale:+e.target.value})}/></label><label>Rotation<input type="range" min="-35" max="35" value={activePlacement.rotation} onChange={e=>updatePlacement({rotation:+e.target.value})}/></label></div></>}</fieldset>}
 <div className="fine-tune"><label>Photo background<input type="color" value={settings.background} onChange={e=>setSettings({...settings,background:e.target.value})}/></label><label>Spacing<input type="range" min="4" max="30" value={settings.gap} onChange={e=>setSettings({...settings,gap:+e.target.value})}/></label><label>Extra caption<input maxLength={48} value={settings.caption} onChange={e=>setSettings({...settings,caption:e.target.value})}/></label></div><button className="primary studio-continue" onClick={onContinue}>Use this design <ArrowRight size={17}/></button></div></section></main>;
}
