import QRCode from 'qrcode';
import {ArrowLeft,ArrowRight,Camera,Check,Copy,Download,FlipHorizontal2,Link2,ShieldCheck,Unplug} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {useCamera} from '../hooks/useCamera';
import {compose} from '../services/composer';
import {LAYOUTS} from '../data/layouts';
import {CustomizationPanel} from './CustomizationPanel';
import {LayoutPreview} from './LayoutPreview';
import type {BoothLayout,BoothSettings,CropState} from '../types';

type ConnectionState='idle'|'waiting'|'connecting'|'connected'|'reconnecting'|'error';
type Stage='entry'|'layout'|'capture';
const PAIR_LAYOUTS=LAYOUTS.filter(layout=>layout.id!=='album-square');
const defaultCrop=():CropState=>({zoom:1,x:0,y:0,brightness:100,contrast:100,filter:'none'});
export const createRoomCode=()=>{const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ',bytes=new Uint8Array(4);crypto.getRandomValues(bytes);return Array.from(bytes,value=>alphabet[value%alphabet.length]).join('')};
const initialDesign=():BoothSettings=>({frame:'#f3effc',background:'#ddd5ef',gap:14,caption:'together, from anywhere',countdown:3,frameStyle:'solid',frameEffect:'natural',photoFilter:'none',photoShape:'rounded',layoutLocked:true,stickers:[],decorationPlacements:{},titleText:'together, from anywhere',footerText:'two cameras · one memory',dateText:new Date().toLocaleDateString(),textColor:'#352a2e',fontStyle:'signature'});

export function PairDevice(){
 const queryRoom=new URLSearchParams(location.search).get('room')?.replace(/[^a-z]/gi,'').slice(0,4).toUpperCase()||'';
 const [stage,setStage]=useState<Stage>('entry'),[state,setState]=useState<ConnectionState>('idle'),[code,setCode]=useState(queryRoom),[qr,setQr]=useState(''),[message,setMessage]=useState(''),[isHost,setIsHost]=useState(false),[countdown,setCountdown]=useState<number|null>(null),[localShots,setLocalShots]=useState<string[]>([]),[remoteShots,setRemoteShots]=useState<string[]>([]),[result,setResult]=useState(''),[pairLayout,setPairLayout]=useState<BoothLayout>(PAIR_LAYOUTS[0]),[design,setDesign]=useState<BoothSettings>(initialDesign),[inverted,setInverted]=useState(true);
 const cam=useCamera(),ws=useRef<WebSocket|null>(null),pc=useRef<RTCPeerConnection|null>(null),channel=useRef<RTCDataChannel|null>(null),remote=useRef<HTMLVideoElement>(null),local=useRef<HTMLVideoElement>(null),incoming=useRef<{parts:string[];total:number;index:number}|null>(null),captureLock=useRef(false),pendingSignals=useRef<unknown[]>([]),pendingCandidates=useRef<RTCIceCandidateInit[]>([]),reconnectTimer=useRef<number|null>(null);
 const envUrl=import.meta.env.VITE_SIGNALING_URL as string|undefined,signalUrl=envUrl||(location.protocol==='https:'?`wss://${location.host}/api/signal`:'ws://localhost:8787');
 const localCount=localShots.filter(Boolean).length,remoteCount=remoteShots.filter(Boolean).length,completedTakes=Math.min(localCount,remoteCount),complete=localCount>=pairLayout.poses&&remoteCount>=pairLayout.poses,readyForNext=localCount===remoteCount&&completedTakes<pairLayout.poses&&countdown===null;
 const sendSignal=(value:unknown)=>{if(ws.current?.readyState===WebSocket.OPEN)ws.current.send(JSON.stringify(value));else pendingSignals.current.push(value)};
 const sendData=(value:unknown)=>channel.current?.readyState==='open'&&channel.current.send(JSON.stringify(value));
 const clearSession=()=>{if(pc.current?.connectionState==='disconnected')return;setCountdown(null);setLocalShots([]);setRemoteShots([]);setResult('');incoming.current=null;captureLock.current=false};
 const stopConnection=()=>{if(reconnectTimer.current)clearTimeout(reconnectTimer.current);ws.current?.close();channel.current?.close();pc.current?.close();cam.stop();ws.current=null;pc.current=null;channel.current=null;pendingSignals.current=[];pendingCandidates.current=[];clearSession();setState('idle');setStage('entry');setQr('');setIsHost(false)};
 const captureLocal=()=>{const v=local.current;if(!v||!v.videoWidth)return'';const maxWidth=1280,maxHeight=960,scale=Math.min(1,maxWidth/v.videoWidth,maxHeight/v.videoHeight),c=document.createElement('canvas');c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);const x=c.getContext('2d')!;if(inverted){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(v,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.82)};
 const sendImage=(image:string,index:number)=>{const dc=channel.current;if(!dc||dc.readyState!=='open')return;const size=48000,total=Math.ceil(image.length/size);dc.send(JSON.stringify({type:'image-start',total,index}));for(let i=0;i<total;i++)dc.send(JSON.stringify({type:'image-chunk',data:image.slice(i*size,(i+1)*size)}));dc.send(JSON.stringify({type:'image-end',index}))};
 const runCapture=(target:number,index:number)=>{if(captureLock.current||index>=pairLayout.poses||localShots[index])return;captureLock.current=true;const timer=window.setInterval(()=>{const left=Math.max(0,Math.ceil((target-Date.now())/1000));setCountdown(left);if(Date.now()>=target){clearInterval(timer);setCountdown(null);const shot=captureLocal();if(shot){setLocalShots(prev=>{const next=[...prev];next[index]=shot;return next});sendImage(shot,index)}captureLock.current=false}},50)};
 const handleData=(raw:string)=>{let data:any;try{data=JSON.parse(raw)}catch{return}if(data.type==='capture-at')runCapture(data.target,data.index);if(data.type==='design'){setDesign(data.settings);const next=PAIR_LAYOUTS.find(l=>l.id===data.layoutId);if(next)setPairLayout(next)}if(data.type==='session-reset')clearSession();if(data.type==='image-start')incoming.current={parts:[],total:data.total,index:data.index};if(data.type==='image-chunk'&&incoming.current){incoming.current.parts.push(data.data);if(incoming.current.parts.length===incoming.current.total){const image=incoming.current.parts.join(''),index=incoming.current.index;setRemoteShots(prev=>{const next=[...prev];next[index]=image;return next});incoming.current=null}}};
 const attachChannel=(dc:RTCDataChannel,host:boolean)=>{channel.current=dc;dc.onopen=()=>{setState('connected');if(host)dc.send(JSON.stringify({type:'design',settings:design,layoutId:pairLayout.id}))};dc.onmessage=e=>handleData(e.data);dc.onclose=()=>{clearSession();setState('reconnecting')}};
 const setup=async(room:string,host:boolean)=>{clearSession();setStage('capture');setCode(room);setIsHost(host);setMessage('');setState(host?'waiting':'connecting');const stream=await cam.start();if(!stream){setState('error');return}const peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});pc.current=peer;stream.getTracks().forEach(track=>peer.addTrack(track,stream));peer.ontrack=e=>{if(remote.current)remote.current.srcObject=e.streams[0]};peer.ondatachannel=e=>attachChannel(e.channel,false);if(host)attachChannel(peer.createDataChannel('petal-capture',{ordered:true}),true);peer.onicecandidate=e=>e.candidate&&sendSignal({type:'signal',room,data:{candidate:e.candidate}});peer.onconnectionstatechange=()=>{if(peer.connectionState==='connected')setState('connected');if(['failed','disconnected','closed'].includes(peer.connectionState)){clearSession();setState('reconnecting')}};const socket=new WebSocket(signalUrl);ws.current=socket;socket.onerror=()=>{setMessage('The pairing endpoint could not be reached. Check the code and try again.');setState('error')};socket.onopen=()=>{socket.send(JSON.stringify({type:host?'create':'join',room}));for(const item of pendingSignals.current)socket.send(JSON.stringify(item));pendingSignals.current=[]};socket.onmessage=async e=>{let m:any;try{m=JSON.parse(e.data)}catch{return}if(m.type==='error'){setMessage(m.message);setState('error');return}if(m.type==='peer-left'){clearSession();setMessage('The other device left. Connect again to start a new session.');setState('reconnecting');return}if(m.type==='peer-joined'&&host){const offer=await peer.createOffer();await peer.setLocalDescription(offer);sendSignal({type:'signal',room,data:{sdp:offer}})}if(m.type==='signal'){if(m.data.sdp){await peer.setRemoteDescription(m.data.sdp);for(const candidate of pendingCandidates.current)await peer.addIceCandidate(candidate);pendingCandidates.current=[];if(m.data.sdp.type==='offer'){const answer=await peer.createAnswer();await peer.setLocalDescription(answer);sendSignal({type:'signal',room,data:{sdp:answer}})}}else if(m.data.candidate){if(peer.remoteDescription)await peer.addIceCandidate(m.data.candidate);else pendingCandidates.current.push(m.data.candidate)}}}};
 useEffect(()=>{if(local.current&&cam.stream.current)local.current.srcObject=cam.stream.current},[cam.status,cam.stream,stage]);
 useEffect(()=>()=>{ws.current?.close();channel.current?.close();pc.current?.close();cam.stop()},[]);
 useEffect(()=>{if(complete)cam.stream.current?.getTracks().forEach(track=>{track.enabled=false})},[complete,cam.stream]);
 useEffect(()=>{if(state==='connected'&&isHost)sendData({type:'design',settings:design,layoutId:pairLayout.id})},[state,isHost,design,pairLayout]);
 useEffect(()=>{if(!complete)return;let live=true;(async()=>{const deviceA=isHost?localShots:remoteShots,deviceB=isHost?remoteShots:localShots,crops=Array.from({length:pairLayout.poses},()=>({...defaultCrop(),filter:design.photoFilter||'none'})),left=await compose(pairLayout,deviceA,design,crops),right=await compose(pairLayout,deviceB,design,crops),strip=pairLayout.kind==='strip',sheet=document.createElement('canvas');if(strip){sheet.width=1600;sheet.height=1900}else{sheet.width=left.width*2+70;sheet.height=left.height}const x=sheet.getContext('2d',{alpha:true})!;x.clearRect(0,0,sheet.width,sheet.height);if(strip){const scale=.82,draw=(canvas:HTMLCanvasElement,cx:number,cy:number,angle:number)=>{x.save();x.translate(cx,cy);x.rotate(angle);x.drawImage(canvas,-canvas.width*scale/2,-canvas.height*scale/2,canvas.width*scale,canvas.height*scale);x.restore()};draw(right,1035,1010,.075);draw(left,565,900,-.06)}else{x.drawImage(left,0,0);x.drawImage(right,left.width+70,0)}if(live)setResult(sheet.toDataURL('image/png'))})();return()=>{live=false}},[complete,localShots,remoteShots,isHost,pairLayout,design]);
 const create=()=>{const room=createRoomCode();QRCode.toDataURL(`${location.origin}${location.pathname}?room=${room}`).then(setQr);void setup(room,true)},join=()=>code.length===4&&void setup(code.toUpperCase(),false),startCapture=()=>{if(!isHost||!readyForNext)return;const index=completedTakes,target=Date.now()+4200;sendData({type:'capture-at',target,index});runCapture(target,index)},catchUp=()=>{if(localCount>=remoteCount||localCount>=pairLayout.poses||countdown!==null)return;runCapture(Date.now()+4200,localCount)},updateDesign=(next:BoothSettings)=>{setDesign(next);sendData({type:'design',settings:next,layoutId:pairLayout.id})},updateLayout=(next:BoothLayout)=>{if(!isHost)return;setPairLayout(next);sendData({type:'design',settings:design,layoutId:next.id})},download=async()=>{const blob=await(await fetch(result)).blob(),name=`petal-paired-${Date.now()}.png`,file=new File([blob],name,{type:'image/png'});if(navigator.canShare?.({files:[file]})&&matchMedia('(max-width:850px)').matches){await navigator.share({files:[file],title:'Transparent paired photobooth strips'});return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 if(stage==='entry')return <main className="pair-page"><span className="eyebrow">PAIR TWO DEVICES</span><h1>Create or join?</h1><p className="lead">The host chooses the layout. A guest joins the existing room directly.</p><div className="pair-options"><section><Link2/><h2>Create a room</h2><p>Choose the layout, then invite the second device.</p><button className="primary" onClick={()=>setStage('layout')}>Choose host layout <ArrowRight/></button></section><section><Camera/><h2>Join a room</h2><p>No layout choice needed—the host already selected it.</p><input value={code} maxLength={4} inputMode="text" autoCapitalize="characters" autoCorrect="off" spellCheck={false} onChange={e=>setCode(e.target.value.replace(/[^a-z]/gi,'').toUpperCase())} placeholder="ABCD" aria-label="Room code"/><button onClick={join} disabled={code.length!==4}>Join existing room</button></section></div></main>;
 if(stage==='layout')return <main className="pair-page pair-layout-step"><button className="text-button pair-back" onClick={()=>setStage('entry')}><ArrowLeft/> Back</button><span className="eyebrow">HOST · STEP 1 OF 4</span><h1>Choose the paired layout</h1><p className="lead">This controls the exact number of synchronized takes on both devices.</p><div className="pair-layout-grid">{PAIR_LAYOUTS.map(item=><button className={pairLayout.id===item.id?'active':''} onClick={()=>setPairLayout(item)} key={item.id}><LayoutPreview layout={item}/><span><strong>{item.name}</strong><small>{item.poses} {item.poses===1?'photo':'photos'} per device</small></span>{pairLayout.id===item.id&&<Check/>}</button>)}</div><button className="primary pair-next" onClick={create}>Create room with {pairLayout.poses} {pairLayout.poses===1?'take':'takes'} <ArrowRight/></button></main>;
 if(state==='error')return <main className="pair-page"><div className="pair-status error"><Unplug/><h2>Couldn’t connect</h2><p>{message||cam.error}</p><button onClick={stopConnection}>Start again</button></div></main>;
 if(state==='reconnecting'&&!complete)return <main className="pair-page"><div className="pair-status"><Unplug/><h2>Device disconnected</h2><p>{message||'For privacy, previous frames were cleared. Both devices must connect again.'}</p><button onClick={stopConnection}>Connect again</button></div></main>;
 return <main className="pair-page paired-session">
  <div className="room-status"><span className={`dot ${state}`}/><strong>{state==='waiting'?'Waiting for the guest device…':state==='connected'?'Both devices connected':'Connecting securely…'}</strong><div className="room-code">{code}<button onClick={()=>navigator.clipboard.writeText(code)} aria-label="Copy room code"><Copy/></button></div>{qr&&state==='waiting'&&<img src={qr} alt={`QR for room ${code}`}/>}<p><ShieldCheck/> Host layout: {pairLayout.name} · {pairLayout.poses} {pairLayout.poses===1?'take':'takes'}</p></div>
  {!complete?<><div className="capture-progress"><span>STEP 3 OF 4 · SYNCHRONIZED CAPTURE</span><strong>Take {Math.min(completedTakes+1,pairLayout.poses)} of {pairLayout.poses}</strong><div>{Array.from({length:pairLayout.poses},(_,index)=><i className={index<completedTakes?'done':index===completedTakes?'current':''} key={index}/>)}</div></div>
   <div className="paired-video"><figure><video ref={local} autoPlay muted playsInline className={inverted?'mirror':''}/><figcaption>This device {localCount}/{pairLayout.poses}</figcaption>{countdown!==null&&<b className="paired-countdown">{countdown||'Smile!'}</b>}</figure><figure><video ref={remote} autoPlay playsInline/><figcaption>Connected device {remoteCount}/{pairLayout.poses}</figcaption></figure>
    <div className="paired-capture-dock"><button className={`mirror-toggle ${inverted?'active':''}`} onClick={()=>setInverted(value=>!value)} aria-pressed={inverted}><FlipHorizontal2 size={17}/> Inverted: {inverted?'On':'Off'}</button>
     {state==='connected'&&isHost&&localCount===remoteCount&&<button className="primary paired-capture" onClick={startCapture} disabled={!readyForNext}><Camera size={18}/>{completedTakes===0?'Take first photo':'Take next photo'}</button>}
     {state==='connected'&&localCount<remoteCount&&<button className="primary paired-capture catch-up" onClick={catchUp} disabled={countdown!==null}><Camera size={18}/> Catch up photo {localCount+1}</button>}
     <span>{localCount<remoteCount?'This device is behind—take only its missing photo.':isHost?'Host controls the synchronized shutter.':'Guest camera ready. The host starts synchronized takes.'}</span>
    </div>
   </div>{localCount!==remoteCount&&<div className="sync-note">The device with fewer photos can use its Catch up button. The completed device will not retake.</div>}</>:<><div className="editor-unlocked"><Check/><span>STEP 4 OF 4</span><h2>All {pairLayout.poses} takes completed</h2><p>The front and back strips export on a transparent canvas.</p></div><div className="paired-editor-grid">{result&&<section className="paired-result transparent-result"><h2>Two-device print</h2><img src={result} alt="Two overlapping transparent photobooth strips"/><button className="primary" onClick={download}><Download/> Download transparent PNG</button></section>}<CustomizationPanel layout={pairLayout} settings={design} onLayout={updateLayout} onChange={updateDesign} allowLayout={isHost}/></div></>}
  <button className="danger" onClick={stopConnection}><Unplug/> Disconnect and clear session</button>
 </main>;
}
