import QRCode from 'qrcode';
import {Camera,Copy,Download,Link2,ShieldCheck,Unplug} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {useCamera} from '../hooks/useCamera';
import {compose} from '../services/composer';
import {LAYOUTS} from '../data/layouts';
import type {CropState} from '../types';

type State='choose'|'waiting'|'connecting'|'connected'|'reconnecting'|'error';
const defaultCrop=():CropState=>({zoom:1,x:0,y:0,brightness:100,contrast:100,filter:'none'});

export function PairDevice(){
  const queryRoom=new URLSearchParams(location.search).get('room')?.slice(0,4).toUpperCase()||'';
  const [state,setState]=useState<State>('choose'),[code,setCode]=useState(queryRoom),[qr,setQr]=useState(''),[message,setMessage]=useState(''),[isHost,setIsHost]=useState(false),[countdown,setCountdown]=useState<number|null>(null),[localShot,setLocalShot]=useState(''),[remoteShot,setRemoteShot]=useState(''),[result,setResult]=useState('');
  const cam=useCamera(),ws=useRef<WebSocket|null>(null),pc=useRef<RTCPeerConnection|null>(null),channel=useRef<RTCDataChannel|null>(null),remote=useRef<HTMLVideoElement>(null),local=useRef<HTMLVideoElement>(null),incoming=useRef<{parts:string[];total:number}|null>(null);
  const envUrl=import.meta.env.VITE_SIGNALING_URL as string|undefined;
  const signalUrl=envUrl||(location.protocol==='https:'?`wss://${location.host}/api/signal`:'ws://localhost:8787');
  const sendSignal=(value:unknown)=>ws.current?.readyState===WebSocket.OPEN&&ws.current.send(JSON.stringify(value));
  const disconnect=()=>{ws.current?.close();channel.current?.close();pc.current?.close();cam.stop();ws.current=null;pc.current=null;channel.current=null;setState('choose');setCountdown(null);setLocalShot('');setRemoteShot('');setResult('')};

  const captureLocal=()=>{const v=local.current;if(!v||!v.videoWidth)return'';const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')!.drawImage(v,0,0);return c.toDataURL('image/jpeg',.86)};
  const sendImage=(image:string)=>{const dc=channel.current;if(!dc||dc.readyState!=='open')return;const size=14000,total=Math.ceil(image.length/size);dc.send(JSON.stringify({type:'image-start',total}));for(let i=0;i<total;i++)dc.send(JSON.stringify({type:'image-chunk',data:image.slice(i*size,(i+1)*size)}))};
  const runCapture=(target:number)=>{const timer=window.setInterval(()=>{const left=Math.max(0,Math.ceil((target-Date.now())/1000));setCountdown(left);if(Date.now()>=target){clearInterval(timer);setCountdown(null);const shot=captureLocal();if(shot){setLocalShot(shot);sendImage(shot)}}},50)};
  const handleData=(raw:string)=>{const data=JSON.parse(raw);if(data.type==='capture-at')runCapture(data.target);if(data.type==='image-start')incoming.current={parts:[],total:data.total};if(data.type==='image-chunk'&&incoming.current){incoming.current.parts.push(data.data);if(incoming.current.parts.length===incoming.current.total){setRemoteShot(incoming.current.parts.join(''));incoming.current=null}}};
  const attachChannel=(dc:RTCDataChannel)=>{channel.current=dc;dc.onopen=()=>setState('connected');dc.onmessage=e=>handleData(e.data);dc.onclose=()=>setState('reconnecting')};

  const setup=async(room:string,host:boolean)=>{setCode(room);setIsHost(host);setMessage('');setState(host?'waiting':'connecting');const stream=await cam.start();if(!stream){setState('error');return}const peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});pc.current=peer;stream.getTracks().forEach(track=>peer.addTrack(track,stream));peer.ontrack=e=>{if(remote.current)remote.current.srcObject=e.streams[0]};peer.ondatachannel=e=>attachChannel(e.channel);if(host)attachChannel(peer.createDataChannel('petal-capture',{ordered:true}));peer.onicecandidate=e=>e.candidate&&sendSignal({type:'signal',room,data:{candidate:e.candidate}});peer.onconnectionstatechange=()=>{if(peer.connectionState==='connected')setState('connected');if(['failed','disconnected'].includes(peer.connectionState))setState('reconnecting')};
    const socket=new WebSocket(signalUrl);ws.current=socket;socket.onerror=()=>{setMessage('The pairing endpoint could not be reached. Solo mode is still available.');setState('error')};socket.onopen=()=>sendSignal({type:host?'create':'join',room});socket.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='error'){setMessage(m.message);setState('error');return}if(m.type==='peer-left'){setState('reconnecting');return}if(m.type==='peer-joined'&&host){const offer=await peer.createOffer();await peer.setLocalDescription(offer);sendSignal({type:'signal',room,data:{sdp:offer}})}if(m.type==='signal'){if(m.data.sdp){await peer.setRemoteDescription(m.data.sdp);if(m.data.sdp.type==='offer'){const answer=await peer.createAnswer();await peer.setLocalDescription(answer);sendSignal({type:'signal',room,data:{sdp:answer}})}}else if(m.data.candidate)await peer.addIceCandidate(m.data.candidate)}};
  };
  useEffect(()=>{if(local.current&&cam.stream.current)local.current.srcObject=cam.stream.current},[cam.status,cam.stream]);
  useEffect(()=>()=>disconnect(),[]);
  useEffect(()=>{if(!localShot||!remoteShot)return;compose(LAYOUTS[2],[isHost?localShot:remoteShot,isHost?remoteShot:localShot],{frame:'#fff5f7',background:'#ead3d9',gap:14,caption:'together, from anywhere',countdown:3},[defaultCrop(),defaultCrop()]).then(c=>setResult(c.toDataURL('image/png')))},[localShot,remoteShot,isHost]);
  const create=()=>{const room=Math.random().toString(36).slice(2,6).toUpperCase();QRCode.toDataURL(`${location.origin}${location.pathname}?room=${room}`).then(setQr);void setup(room,true)};
  const join=()=>code.length===4&&void setup(code.toUpperCase(),false);
  const startCapture=()=>{const target=Date.now()+4200;channel.current?.send(JSON.stringify({type:'capture-at',target}));runCapture(target)};
  const download=()=>{const a=document.createElement('a');a.href=result;a.download=`petal-paired-${Date.now()}.png`;a.click()};

  return <main className="pair-page"><span className="eyebrow">TWO CAMERAS, ONE MEMORY</span><h1>Pair another device</h1><p className="lead">Connect directly with WebRTC. Photos travel encrypted peer-to-peer; the Vercel signaling function only introduces the devices.</p>{state==='choose'?<div className="pair-options"><section><Link2/><h2>Create a room</h2><p>Get a private four-letter code and QR to share.</p><button className="primary" onClick={create}>Create room</button></section><section><Camera/><h2>Join a room</h2><p>Enter the code shown on the host device.</p><input value={code} maxLength={4} inputMode="text" autoCapitalize="characters" onChange={e=>setCode(e.target.value.replace(/[^a-z]/gi,'').toUpperCase())} placeholder="ABCD" aria-label="Room code"/><button onClick={join} disabled={code.length!==4}>Join room</button></section></div>:state==='error'?<div className="pair-status error"><Unplug/><h2>Couldn’t connect</h2><p>{message||cam.error}</p><button onClick={disconnect}>Back</button></div>:<><div className="room-status"><span className={`dot ${state}`}/><strong>{state==='waiting'?'Waiting for the other device…':state==='connected'?'Devices connected':state==='reconnecting'?'Connection interrupted…':'Connecting securely…'}</strong><div className="room-code">{code}<button onClick={()=>navigator.clipboard.writeText(code)} aria-label="Copy room code"><Copy size={16}/></button></div>{qr&&state==='waiting'&&<img src={qr} alt={`QR code to join room ${code}`}/>}<p><ShieldCheck size={16}/> Both people explicitly approve camera access.</p></div><div className="paired-video"><figure><video ref={local} autoPlay muted playsInline/><figcaption>This device {localShot&&'✓ captured'}</figcaption>{countdown!==null&&<b className="paired-countdown">{countdown||'Smile!'}</b>}</figure><figure><video ref={remote} autoPlay playsInline/><figcaption>Connected device {remoteShot&&'✓ received'}</figcaption></figure></div>{state==='connected'&&isHost&&!result&&<button className="primary paired-capture" onClick={startCapture} disabled={countdown!==null}>Start synchronized capture</button>}{state==='connected'&&!isHost&&!localShot&&<div className="sync-note">The host controls the capture. Get ready for the shared countdown.</div>}{result&&<section className="paired-result"><h2>Your shared keepsake</h2><img src={result} alt="Paired photobooth result"/><button className="primary" onClick={download}><Download size={17}/> Download result</button></section>}<div className="sync-note">Capture is near-simultaneous using a shared timestamp; different devices cannot guarantee the exact same camera frame.</div><button className="danger" onClick={disconnect}><Unplug size={17}/> Disconnect and stop cameras</button></>}</main>;
}
