import React from 'react';
import ReactDOM from 'react-dom/client';
import { Analytics } from '@vercel/analytics/react';
import { App } from './App';
import './styles.css';
import './mobile.css';
import './layout-designs.css';
import './custom-studio.css';
import './custom-shapes.css';
import './materials.css';
import './effects-editor.css';
import './post-designer.css';
import './capture-flow.css';
import './camera-lenses.css';
import './paired-flow.css';
import './paired-fixes.css';
import './lavender-theme.css';
import './ux-fixes.css';

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/><Analytics/></React.StrictMode>);
